"""Publish the completed expansion without rebuilding older frozen research."""
from pathlib import Path
from datetime import datetime,timezone
from collections import Counter
import json,platform,importlib.metadata,re
import pandas as pd
from full_catalogue_options import save,sha
HERE=Path(__file__).resolve().parent;OUT=HERE/'ensemble';DATA=HERE/'data_expansion';OW=HERE/'options_weekly'

def load(p):return json.loads(Path(p).read_text())
def pct(v):return f'{v*100:,.2f}%'
def table(rows,keys,labels):
    return '\n'.join(['| '+' | '.join(labels)+' |','| '+' | '.join(['---']*len(keys))+' |']+['| '+' | '.join(str(row[k]) for k in keys)+' |' for row in rows])

def write_report(path,text):
    # Keep code/link identifiers intact while separating compact numeric prose.
    links=[]
    def protect(m):links.append(m[0]);return f'@@LINK{len(links)-1}@@'
    text=re.sub(r'\[[^\]]*\]\([^)]*\)',protect,text)
    text=re.sub(r'\b\d{4}-\d{2}-\d{2}T[\d:.+]+',protect,text)
    for a,b in {'percontractperside':'per contract per side','perpoint':'per point','perweek':'per week','perfill':'per fill','NewYorkmidnight':'New York midnight','APIrecords':'API records','firstensemble':'first ensemble','paperfamilies':'paper families','dailyPF':'daily PF','PFfamily':'PF family','EScomparator':'ES comparator','EuropeanFridayweeklies':'European Friday weeklies','account attempts':'account attempts','minuteclose':'minute close','CPIAUCSL/CPILFESL':'CPIAUCSL / CPILFESL','calendar-aware':'calendar-aware','quarterpilot':'quarter pilot','quarterspilot':'quarters pilot','fullperiod':'full period','full-catalogue':'full-catalogue','paper-inspired':'paper-inspired','ALFREDinflation':'ALFRED inflation','COTarchives':'COT archives','DBCdailyprices':'DBC daily prices','ESoptionquotes':'ES option quotes','COTpublication':'COT publication','knownunresolved':'known unresolved','five-eventchain':'five-event chain','PPOmodels':'PPO models','TensorTradePPO models':'TensorTrade PPO models','counterparty':'counterparty','current_coverage.jsonsupersedes':'current_coverage.json supersedes','all-cash':'all-cash','seeds peryear':'seeds per year','peryearandmarket':'per year and market','peryear':'per year','price history':'price history','prior15minuteclose':'prior 15-minute close','beforefirstoutput':'before first output'}.items():text=text.replace(a,b)
    text=re.sub(r'(?<=[A-Za-z])(?=\d)|(?<=\d)(?=[A-Za-z])',' ',text)
    text=re.sub(r'%(?=[A-Za-z])','% ',text)
    text=re.sub(r',(?=[A-Za-z])|;(?=[\w$])',lambda m:m[0]+' ',text)
    text=re.sub(r'(?<=[A-Za-z]),(?=\d)|,(?=\d{4}\b)',', ',text)
    text=re.sub(r'(?<=[A-Za-z]):(?=\d)',': ',text)
    text=re.sub(r'(?<=[A-Za-z])\$',' $',text)
    for a,b in {'AppleSECfacts':'Apple SEC facts','Databentoactual':'Databento actual','endsSeptember':'ends September','MondayJune':'Monday June','fixedMonday':'fixed Monday','exitWednesday':'exit Wednesday','beginningDecember':'beginning December','wasDecember':'was December','leastOctober':'least October','futuresPF':'futures PF','quarterlyEPS':'quarterly EPS'}.items():text=text.replace(a,b)
    for a,b in {'bpcommission':'bp commission','bpslippage':'bp slippage','scheduledweeks':'scheduled weeks','EScomparators':'ES comparators','episodepilot':'episode pilot','mcapital':'m capital','past-closes':'past closes','modelhashes':'model hashes','Pineinventory':'Pine inventory','year2026':'year 2026','minuteBTC':'minute BTC','minutePF':'minute PF'}.items():text=text.replace(a,b)
    for k,link in enumerate(links):text=text.replace(f'@@LINK {k}@@',link)
    text=text.replace('C 7/C 8/C 11','C7/C8/C11').replace('$1 m','$1 million').replace('Q 4','Q4').replace('ranMarch','ran March')
    path.write_text(text)

def main():
    validation=load(OUT/'validation.json');om=load(OW/'manifest.json');options=load(OW/'results.json')
    assert om['planned_weeks']==52
    at=datetime.now(timezone.utc).isoformat();ensemble_rows=[];manifests={};tables=[];pf=set();coverage=[]
    for market in ['US_ETF_portfolio','BTC_daily']:
        folder=OUT/market;rows=load(folder/'results.json');ensemble_rows.extend(rows);manifests[market]=load(folder/'manifest.json')
        records=load(folder/'coverage.json');coverage.extend(dict(r,experiment=market) for r in records)
        pf.update(r['name'] for r in records if r['family']=='PatternFindr')
        for row in rows:
            if row['block']!='full' or row['case']!='base':continue
            h=pd.read_parquet(folder/'ledgers'/(row['method']+'_base.parquet'));exposure=float(((h.equity-h.cash)/h.equity).mean())
            tables.append({'market':market,'method':row['method'],'return':pct(row['total_return']),'dd':pct(row['max_drawdown']),'benchmark':pct(row['benchmark_return']),'benchmark_dd':pct(row['benchmark_drawdown']),'mean_exposure':pct(exposure)})
    intraday=[];allclocks=[]
    for root in ['ES','GC','CL','BTC']:
        folder=OUT/'intraday'/root;rows=load(folder/'results.json');ensemble_rows.extend(rows);manifests[root]=load(folder/'manifest.json')
        for r in load(folder/'sources.json')['shadow_books']:
            coverage.append(dict(r,experiment=root));
            if r['family']=='PatternFindr':pf.add(r['name'])
        for r in rows:
            if r['block']=='full' and r['case']=='base':intraday.append({'market':root,'method':r['method'],'return':pct(r['total_return']),'dd':pct(r['max_drawdown']),'benchmark':pct(r['benchmark_return']),'benchmark_dd':pct(r['benchmark_drawdown'])})
    for root in ['ES','CL']:
        folder=OUT/'all_clocks'/root;rows=load(folder/'results.json');ensemble_rows.extend(rows);manifests[root+'_all_clocks']=load(folder/'manifest.json')
        for r in load(folder/'sources.json')['shadow_books']:
            if r.get('clock')=='daily':pf.add(r['name']);coverage.append(dict(r,experiment=root+'_all_clocks'))
        for r in rows:
            if r['block']=='full' and r['case']=='base':allclocks.append({'market':root,'return':pct(r['total_return']),'dd':pct(r['max_drawdown']),'benchmark':pct(r['benchmark_return']),'benchmark_dd':pct(r['benchmark_drawdown'])})
    assert len(pf)==86
    assert not any(bool(m['all_gates_pass']) for m in manifests.values()),'Report qualification text needs review'
    consideration=[]
    for row in load(HERE/'extension/patternfindr_configs.json'):
        consideration.append({'id':row['id'],'included':row['id'] in pf,'reason':'Saved causal shadow book included; original settings retained.' if row['id'] in pf else 'No compatible verified saved book: see earlier per-config readiness/status; no performance-based exclusion.'})
    save(OUT/'research_scope.json',{'at':at,'shadow_book_instances':len(coverage),'included_patternfindr_configurations':len(pf),'patternfindr':consideration,
      'quant':'All four previously retested families represented: ES C7/C8/C11 and BTC TVRange Reversal64k. 176 inventoried Pine files contain variants/other families; they are NOT176 independently replicated and investable algorithms.',
      'paper':'Compatible daily long-only price, reversal, risk, ML, sector and multiasset books plus completed-day futures rules enter. Long/short sector books, factor explanatory regressions, specialized derivative/credit/property constructions and newly added filing/macro pilots remain separate experiments. An unpriced or noncausal signal does not gain valid returns by being averaged.',
      'tensortrade':'42 fresh annual expanding-window PPO fits in TensorTrade environment,3fixed seeds peryear andmarket. Old optimized model files are not deployed on dates that trained them. Ridge, fixed and adaptive weighting are compared without selecting a winning seed.',
      'coverage_addendum':'Five daily futuresPF books were added in separately registered all_clocks extension after firstensemble outputs; earlier results preserved. No favorable-result filter.',
      'books':coverage})
    report=[f'Ensemble research completed {at}.\n',
      'The combinations generally made the ride smoother but earned less. No ensemble passed the requirement of higher after-cost return with no worse drawdown across the full sample, separate calendar years and the cost/delay checks. The frozen prospective simulation remains a separate experiment.\n',
      'In plain language, each strategy supplied its latest desired investment. Similar strategies first voted within a family, and the families then shared the account. The account bought and sold real historical instruments at the next permitted opening price and paid its own modeled costs. Adding old profit curves would not establish that these combined trades were possible.\n',
      f'The study used {len(coverage)} saved shadow-book instances, including all86previously tested Pattern_FindR configurations, four retested quant families, paper-inspired families and TensorTrade. It ran {len(ensemble_rows)} candidate cases. These are overlapping methods, markets, time windows and stresses—not that many independent strategies. Thirty futures cases are exact WithoutQuant/EqualFamilies aliases in GC/CL; {len(ensemble_rows)-30} remain after those aliases.\n',
      'Daily tests span2020 through September2026, with2017-19initial training. The US15ETF panel endsSeptember21; BTC endsSeptember23. Seven weighting methods were fixed: equal families, inverse volatility, past Sharpe, ridge return forecast, TensorTrade PPO, equal/PPO50:50, and an omission-of-Pattern_FindR control. All results below are cumulative returns, not annual returns. Drawdown means the biggest fall from a previous account peak.\n',
      table(tables,['market','method','return','dd','benchmark','benchmark_dd','mean_exposure'],['Market','Method','Return after costs','Maximum daily drawdown','Buy-and-hold return','Buy-and-hold drawdown','Mean invested fraction']),
      '\nLower investment exposure helps explain the smaller drawdowns and lower returns; it is not evidence of a profitable forecasting edge. Removing Pattern_FindR improved some retrospective comparisons. That observation does not authorize replacing the frozen candidates or selecting a new model on this same history.\n',
      'TensorTrade trained42PPO models: seven annual folds × two markets × three fixed seeds,16384steps each,688128steps total. Each fold used only earlier data, averaged every seed and retained the last fixed-budget checkpoint. Ridge used21-session labels that had fully matured before each fold. Weekly execution decisions used completed closes; cost and extra-delay stresses replayed the same target streams. Existing expert parameters and these historical samples had already been explored, so these are retrospective walk-forward tests, not untouched holdouts.\n',
      'US costs were5bpcommission+5bpslippage per side; BTC10bp+5bp. Doubled-cost and one-additional-bar execution delays were tested. US idle cash earned a lagged bill-yield convention; BTC cash earned zero. Distributions were explicit and passive holdings reinvested them. The inherited daily performance helper uses252for annualized volatility/Sharpe even on BTC; those fields are not used for the gate or the comparisons here.\n',
      'Futures blends used actual ES/GC/CL contracts, integer quantities, both sides of every roll, $1mcapital,95%target exposure, $2.50per contract per side and one tick, with three-tick and extra15minute-delay stresses. The comparator is the same passively rolled future at95%initial gross, with the same opening risk cap. Date range2023-June2026. Borrow/margin schedules and actual bid/ask execution are not verified.\n',
      table(intraday,['market','method','return','dd','benchmark','benchmark_dd'],['Market','Method','Return','Maximum daily drawdown','Matched passive return','Passive drawdown']),
      '\nThe BTC15m branch evaluates2025-May2026, using2024as warmup. Its comparator is fully invested spot BTC. The blends trade daily targets observed on the prior15minuteclose; they do not copy the experts’ intrabar stops. Short borrowing is modeled at5%/10% and collateral at1.5times short proceeds; historical borrow availability is unverified. Several blends lost less than passive BTC, but they still lost money and failed the all-period gate.\n',
      'The separate coverage extension includes all five saved daily futuresPF books, combining their last completed-day targets with the15minutePF books inside one PFfamily. This was registered after the firstensemble results to fill an input-coverage omission; it is not a fresh untouched test.\n',
      table(allclocks,['market','return','dd','benchmark','benchmark_dd'],['All-clocks blend','Return','Drawdown','Passive return','Passive drawdown']),
      '\nNo newly tested model is execution-qualified. No new winning top-ten list or Pine promotion was made. The existing ten exploratory Pine artifacts remain research views. Multiasset trading and annually retrained PPO would require a verified external execution/model integration; a Pine plot alone would not reproduce these accounts.\n',
      'Our [Pine readiness assessment](pine_readiness.json) distinguishes plotting a signal from reproducing account returns. TradingView documents chart-based broker emulation and financial/economic data requests; those capabilities do not by themselves reproduce our dated-source, multiasset execution. [Official Pine strategy documentation](https://www.tradingview.com/pine-script-docs/concepts/strategies/), [data requests](https://www.tradingview.com/pine-script-docs/concepts/other-timeframes-and-data/).\n',
      f'Validation: {validation["actual_price_accounts_replayed"]}saved accounts independently replayed at every mark; {validation["account_rows_replayed"]:,}account rows checked. Source hashes,42model hashes,14annual fold cutoffs and the frozen five-event chain were checked. Full suite: {validation["tests_passed"]}passed; focused expansion checks are also recorded. See [validation](validation.json), [input coverage](research_scope.json), [full case results](all_results.json), and [comparison chart](comparison.png).\n']
    write_report(OUT/'REPORT.md','\n'.join(report));save(OUT/'all_results.json',ensemble_rows)
    data_rows=load(DATA/'filing_results.json')+load(DATA/'macro_results.json');data_summary=[]
    for r in data_rows:
        if r['block']=='full' and r['case']=='base':data_summary.append({'section':r['section'],'strategy':r['strategy'],'return':pct(r['total_return']),'dd':pct(r['max_drawdown']),'benchmark':pct(r['benchmark_return']),'benchmark_dd':pct(r['benchmark_drawdown'])})
    macroblocks=[{'block':r['block'],'return':pct(r['total_return']),'benchmark':pct(r['benchmark_return']),'pass':r['pass']} for r in data_rows if r['strategy']=='InflationAllocation' and r['case']=='base']
    data_report=[f'Dated-data expansion completed {at}.\n',
      'Three additional paper sections received limited historical adapter tests,48candidate cases including period and execution stresses. These are explicitly adapted rules, not exact cross-sectional reproductions of the paper.\n',
      table(data_summary,['section','strategy','return','dd','benchmark','benchmark_dd'],['Paper section','Adapter','Return','Drawdown','Buy-and-hold return','Buy-and-hold drawdown']),
      '\n§3.2 asks whether unexpectedly strong earnings help predict returns. This pilot used Apple’s first-filed, explicitly tagged quarterly diluted EPS and dated SEC acceptance information. It compared the latest quarter with four quarters earlier, scaled by the variation in eight such surprises. Positive scores meant Apple, otherwise cash, decided monthly and executed next open. The paper instead ranks many stocks and buys/sells opposite deciles; this pilot does not reproduce that portfolio.\n',
      'The API supplied67direct quarterly EPS records. Twelve consecutive quarters were required for a score; valid monthly scores ranMarch2018-January2022. Later missing Q4 tags broke continuity. Missing values were retained as unavailable and the account stayed in cash; annual weighted EPS was not subtracted to invent Q4. The actual evaluation spans2018-September2026, so later cash returns must not be described as later earnings-trading evidence.\n',
      '§3.3 compares accounting book value with market value. The Apple adapter bought only when its positive book/market ratio exceeded its preceding monthly median, with at least12prior observations. It never triggered in this sample. Its26.60%base gain was cash interest, with zero stock trades; it is an evaluated all-cash rule, not evidence of a successful value strategy. No return-driven threshold adjustment was made.\n',
      'A filing-date split-basis correction was made before reviewing performance: historical reported share counts should be advanced through splits after their filing basis, not blindly from the older balance-sheet date. Initial code/protocol/results remain in filing_pre_basis_correction/. Both SEC adapters require current-enough fundamentals and defer date-only disclosures until at least the next NewYorkmidnight and recorded acceptance+1minute. [SEC API documentation](https://www.sec.gov/search-filings/edgar-application-programming-interfaces) describes companyfacts and submission access.\n',
      '§19.3 uses the gap between headline and core inflation to set a commodity allocation. The paper formula is clip((headlineYoY−coreYoY)/headlineYoY,0,1); a near-zero denominator sets commodity weight0. The formula is applied literally even during deflation, when its behavior can differ from the usual positive-inflation interpretation. This adapter uses DBC for commodities and SPY for the balance, monthly next-open execution, explicit distributions and trading costs. Both inflation series use seasonally adjusted levels to compute year-over-year changes.\n',
      'The official ALFRED downloads contain1360dated observation versions for CPIAUCSL/CPILFESL, covering2015-August2026. Every decision selects only versions available by that date, using a conservative vintage-date+1day convention. It ignores future vintage end dates. Latest common observations and their year-earlier values must exist; observation/release age limits are90/75days. [ALFRED’s download documentation](https://alfred.stlouisfed.org/help/downloaddata) explains these vintage intervals.\n',
      table(macroblocks,['block','return','benchmark','pass'],['Inflation test period','Strategy return','SPY return','Return/drawdown pass']),
      '\nThe inflation adapter passed the full-period comparison and its three full-period stresses, but missed the return requirement in2017-19and2023onward. It is an interesting hypothesis, not a validated winner. No parameters or thresholds were retuned after these results.\n',
      'Additional public data: eleven CFTC annual archives yielded155787position observations across650market codes,2016-September2026. These are normalized in cot_observations.parquet, with publication time deliberately null. The official FAQ says a complete historical release-date list is unavailable; holidays and shutdowns can delay publication. This prevents treating Tuesday measurements as Tuesday trading signals. §9.2 remains blocked pending release evidence and a broad mapped commodity trading universe. [CFTC documentation](https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm).\n',
      'Individual-bond/credit tests remain blocked. FINRA’s enhanced history requires an agreement and fees, and its academic dataset is restricted to higher-education institutions. Trade prints alone also do not provide two-sided executable quotes, full cash-flow terms, recoveries or funding histories. No purchase was made. [FINRA historical-data terms](https://www.finra.org/filing-reporting/trace/historic-academic-data). The concrete required tables and acquisition findings are in [acquisition_requirements.json](acquisition_requirements.json).\n',
      'The source locations were searched through existing inventories and relevant filenames; no usable local bond/credit release dataset was found. This does not establish what subscriptions the user may have elsewhere. DBC was newly downloaded through yfinance; existing Yahoo/Databento/Bitstamp source snapshots were reused. Direct ALFRED requests stalled; the official browser download forms succeeded. The required provider-directory CLI lookup failed with its own user-agent validation; official provider documentation supplied the fallback.\n']
    write_report(DATA/'REPORT.md','\n'.join(data_report))
    candidates=[r for r in options if r['section']!='ScheduledES'];completed=[r for r in candidates if r['complete']];halted=[r for r in candidates if not r['complete']]
    failures=Counter(r['halted']['reason'] for r in halted);option_table=[]
    for r in candidates:
        option_table.append({'section':r['section'],'case':r['case'],'status':'complete' if r['complete'] else 'HALTED '+r['halted']['week'],'closed':r['entered_weeks'],'cash':r['cash_weeks'],'return':pct(r['full_year_return']) if r['complete'] else 'UNKNOWN','gap_marks':r['unobserved_marks']})
    qpaths=list((OW/'options').glob('*/quotes_*.parquet'));defpaths=list((OW/'options').glob('*/definitions.parquet'))
    write_report(OW/'REPORT.md','\n'.join([f'Weekly options extension completed {at}.\n',
      f'Quote data were prepared for all52scheduled weeks: MondayJune30,2025through MondayJune22,2026. Each account then ran only until its first unresolved failure. All58paper option constructions were evaluated at base bid/ask costs and with an extra adverse tick:116candidate account attempts plus2scheduled-EScomparators. {len(completed)}candidate accounts completed the schedule; {len(halted)}halted. A halt is a failed or unresolved backtest, not a zero return or a trade to drop.\n',
      f'The archive produced{len(qpaths)}quote-day extracts and{len(defpaths)}definition extracts. Entry was fixedMonday14:00UTC, exitWednesday19:55UTC; EuropeanFridayweeklies, prior-listed strikes, the same underlying future and the earlier registered selection rule. Starting cash$1m, one construction unit perweek, $50perpoint, observed bid/ask plus$2.50percontractperside; extra-tick case adds0.25points perfill. Realized dollars carry forward, with no weekly recapitalization or position-size compounding.\n',
      'Missing definitions or valid entry quotes mean no entry. If a position could enter but a required later exit/valuation failed, the account stops. Known entry fills and unresolved quantities are retained in the halt record; terminal equity and full-year return are null. Files for the settled portion show only previously closed weeks, and must not be mistaken for the whole account’s wealth. The script never resumes by skipping the unresolved week.\n',
      'Failure reasons: '+json.dumps(dict(failures))+'.\n',
      'The largest failure group was Christmas week:82of116candidate accounts stopped in the week beginningDecember22,2025;34stopped earlier. The scheduled exit wasDecember24at19:55UTC, but the underlying future’s last extracted quote that day was18:16UTC. This demonstrates a data/timetable mismatch; it does not certify the exchange’s exact closing time. A separately registered calendar-aware execution protocol and endpoint quote checks are needed. The present results retain the original fixed timetable and its failures.\n',
      'Drawdowns use available daytime five-minute liquidation marks only. Overnight moves, missing marks, actual quote-update ages, simultaneous leg fills, exercise/assignment, dated margin and financing are not verified. A week with no entry remains cash. The separate EScomparator trades the same weekly schedule; it is not a fully invested buy-and-hold hurdle. No annualization, performance ranking of halted accounts or execution qualification is supplied.\n',
      table(option_table,['section','case','status','closed','cash','return','gap_marks'],['Paper section','Case','Status','Closed weeks','Cash weeks before stop','Full schedule return','Missing intraperiod marks']),
      '\nSee [events](events.json), [results](results.json), [protocol](protocol.json) and the original immutable episode engine in full_catalogue_options.py. These constructions were already covered by the earlier12episodepilot; this extension adds duration/accounting scrutiny, not58new catalogue entries.\n']))
    catalogue=load(HERE/'full_catalogue/coverage.json')
    for r in catalogue:
        if r['section'] not in ['3.2','3.3','19.3']:continue
        r['prior_status_before_expansion']=r['status'];r['status']='historical_adaptation';r['qualified']=False
        r['historical_completed_cases']=16;r['evidence']=[('data_expansion/macro_results.json' if r['section']=='19.3' else 'data_expansion/filing_results.json')]
        r['notes']={'3.2':'Limited Apple time-series SUE adapter, not paper decile long/short portfolio.2018-2026 evaluation; usable signalMarch2018-Jan2022only, later missing consecutive quarters =>cash.', '3.3':'Limited Apple monthly time-series book/market adapter. No entry triggered; results are cash interest. Original cross-sectional value portfolio remains untested.', '19.3':'Dated ALFRED inflation/DBC-SPY monthly ETF adapter;2017-Sep2026. Fullperiodpass, failures2017-19and2023onward;noqualification.'}[r['section']]
    counts=dict(Counter(r['status'] for r in catalogue));save(HERE/'current_coverage.json',catalogue)
    summary={'at':at,'ensemble_candidate_cases':len(ensemble_rows),'ensemble_exact_alias_cases':30,'ensemble_cases_excluding_exact_aliases':len(ensemble_rows)-30,'saved_shadow_book_instances':len(coverage),'patternfindr_configs_in_ensembles':86,'ppo_fits':42,'ppo_steps':688128,'filing_macro_candidate_cases':len(data_rows),'weekly_options':om,'validation':validation,'catalogue_counts':counts,'qualified_new_strategies':0,'all_catalogue_historically_complete':False,
      'sources':{str(p.relative_to(HERE)):sha(p) for p in [OUT/'all_results.json',OUT/'research_scope.json',DATA/'filing_manifest.json',DATA/'macro_manifest.json',DATA/'cot_manifest.json',OW/'manifest.json',OUT/'validation.json']}}
    save(OUT/'manifest.json',summary)
    depnames=['ensemble_study.py','ensemble_intraday.py','ensemble_btc_intraday.py','ensemble_all_clocks.py','filing_study.py','macro_study.py','options_weekly.py','cot_inventory.py','full_catalogue_options.py','run_study.py','signed_study.py','futures_intraday_retest.py','intraday_common.py','expansion_validate.py','ensemble_report.py']
    save(OUT/'reproducibility.json',{'recorded_at':at,'scope':'Final code/environment provenance, not a claim these dependency hashes were precommitted. Candidate protocols were registered before their own scoring except the explicitly disclosed mechanical correction and coverage addendum.','python':platform.python_version(),'packages':{n:importlib.metadata.version(n) for n in ['numpy','pandas','torch','stable-baselines3','tensortrade','scikit-learn','yfinance','databento']},'code_sha256':{n:sha(HERE/n) for n in depnames}})
    prior=load(HERE/'history/2026-10-03-full-catalogue/current_manifest.json');prior.update({'asof':at,'historically_tested_catalogue_entries':counts['historical_adaptation'],'historical_any_scope_catalogue_entries':counts['historical_adaptation']+counts['historical_episode_only'],'catalogue_status':counts,'unit_and_regression_checks_passed':validation['tests_passed'],'ensemble_expansion':summary,'previous_checkpoint':'history/2026-10-03-full-catalogue/current_manifest.json','remaining_work':['Full historical catalogue remains incomplete. See current_coverage.json and specialized acquisition requirements.','No new strategy is execution-qualified; weekly option halts and sparse earnings disclosures remain failures/limitations.','Keep the four frozen forward candidates and observation through at leastOctober2027 unchanged.']})
    save(HERE/'current_manifest.json',prior)
    overview=[f'Current research results — {at}\n',
      f'Completed {len(ensemble_rows)}ensemble candidate cases,48filing/inflation cases and116weekly option account attempts. Zero newly qualified strategies. The whole paper is still not fully historically tested.\n',
      'The blends combine paper-inspired strategies, all86previously tested Pattern_FindR configurations, four retested quant families and42fresh TensorTradePPO models. Daily blends generally reduced drawdowns but lagged buy-and-hold. Similar models vote within families; actual combined orders pay costs. Existing price history and old expert settings had already been explored, so walk-forward results are retrospective.\n',
      '| Test | Strategy cumulative return | Buy-and-hold return | Strategy / passive drawdown |\n| --- | --- | --- | --- |\n| US ETF equal-family blend,2020–Sep2026 | +59.24% | +162.56% |10.45% /33.70% |\n| US ETF TensorTradePPO,2020–Sep2026 | +54.29% | +162.56% |9.28% /33.70% |\n| BTC equal-family blend,2020–Sep2026 | +181.32% | +1069.31% |30.69% /76.63% |\n| Inflation allocation,2017–Sep2026 | +322.36% | +296.61% |33.13% /33.70% |\n',
      'The inflation adapter beat SPY over the full sample, including cost/delay stresses, but missed the return requirement in2017-19and2023onward. The Apple earnings adapter had large disclosure gaps; the value rule never entered and earned only cash interest. These are not newly proven winners.\n',
      f'Weekly options:52scheduled weeks,58constructions,two cost cases. {len(completed)}candidate account attempts completed and{len(halted)}halted. Full-schedule return remains UNKNOWN for each halted account; known unresolved entries are retained. Missing exits are never discarded or followed by a fictional restart.\n',
      f'Catalogue accounting now has{counts["historical_adaptation"]}limited historical adaptations,{counts["historical_episode_only"]}quote-episode entries,{counts["synthetic_construction_only"]}synthetic-only entries,{counts["blocked_data_or_model"]}blocked entries and2excluded noncandidates. Thus102of175catalogue rows have some historical evidence, including the all-cash value adapter; this is not102faithful full replications. The weekly extension does not add58new entries.\n',
      'New data: dated AppleSECfacts/submissions;1360ALFREDinflation versions;11COTarchives with155787observations; DBCdailyprices; broader local ESoptionquotes. Existing Yahoo stock/ETF/BTC, Bitstamp15minuteBTC, Databentoactual futures and sanitized PF/quant snapshots were reused. COTpublication timing and specialized bond/credit/event/property inputs remain incomplete.\n',
      f'Checks: {validation["tests_passed"]}tests passed;{validation["actual_price_accounts_replayed"]}accounts replayed across{validation["account_rows_replayed"]:,}marks;{validation["weekly_option_accounts_reconciled"]}weekly settled subaccounts reconciled;{validation["weekly_extract_hash_checks"]}weekly extracts hash-checked. Model hashes/fold cutoffs and the frozen source hashes/five-eventchain are valid. The maximum accounting discrepancy was${validation["max_accounting_error_dollars"]:.9f}.\n',
      'Read [ensemble results](ensemble/REPORT.md), [dated data and limitations](data_expansion/REPORT.md), [weekly options](options_weekly/REPORT.md), [current 175-row coverage](current_coverage.json), and [comparison chart](ensemble/comparison.png). Original full-catalogue reports remain a preserved earlier batch; current_coverage.jsonsupersedes their status counts.\n',
      'No actual trades, external messages, new Pine promotion or edits to the frozen four-candidate forward simulation. Continue its precommitted observation through at leastOctober2027. The next meaningful research steps are documented release timestamps and broader dated fundamentals/credit inputs, plus an independently registered calendar-aware options protocol—not tuning today’s failed tests into a historical winner.\n']
    write_report(HERE/'CURRENT_RESULTS.md','\n'.join(overview))
    (HERE/'STATE.md').write_text(f'''# Research checkpoint {at}

Latest user: do the next steps and consider ensembling all previous research with TensorTrade. Read CURRENT_RESULTS.md and REPORT.md in ensemble/, data_expansion/ and options_weekly/. current_coverage.json is the latest 175-row overlay. Preserve the older full_catalogue/ batch. Previous checkpoint: history/2026-10-03-full-catalogue/.

Ensembles: {len(ensemble_rows)} candidate cases including 30 exact GC/CL aliases; {len(coverage)} saved shadow-book instances; all 86 previously tested Pattern_FindR configurations, four retested quant families, paper families and 42 fresh PPO models (688128 steps). Daily tests 2020–Sep2026; actual futures 2023–Jun2026; BTC15m 2025–May2026. Separate all_clocks extension added five daily PF futures books after the first outputs, preserving earlier results. Zero all-period/stress qualifiers. No Pine promotion. The 176-file Pine inventory does not mean 176 replicated algorithms.

Dated data: 48 cases across Apple first-filed SUE, book/market and ALFRED inflation/DBC-SPY. Inflation passes the full sample but fails two other periods. SUE scores exist March2018–January2022 only; later missing quarters mean cash. Value rule never entered. Filing split-basis correction archived before performance inspection in data_expansion/filing_pre_basis_correction/. COT: 11 archives,155787 rows,650 market codes, published_at remains NULL; causal COT test blocked. FINRA/Treasury acquisition requirements documented; no purchases.

Weekly options: 52 scheduled weeks June30,2025–June22,2026;58 constructions ×2 cases;{len(completed)} completed and {len(halted)} halted candidate accounts. Dollar profits/losses carry forward with no recapitalization. Missing required exit stops the series, preserves known entry/unresolved position and leaves full_year_return NULL. Settled subaccount wealth is NOT whole-account wealth after a halt. No annualization, overnight/margin/simultaneous-fill proof or qualification.

Coverage counts: {json.dumps(counts)}. Historical evidence of ANY scope in 102/175 rows, including limited/all-cash adapters. Full historical catalogue remains incomplete. Validation: {validation['tests_passed']} tests; {validation['actual_price_accounts_replayed']} price accounts replayed; {validation['weekly_option_accounts_reconciled']} weekly settled subaccounts reconciled; {validation['weekly_extract_hash_checks']} extracts checked;42 model hashes and14 folds checked. Frozen chain of {validation['frozen_events']} events valid.

NEVER modify prospective.py, src/tensortrade_lab/portfolio.py, prospective/freeze.json or prior events/snapshots. Freeze v2:2026-10-02T19:23:59.611201Z; same four candidates. Daily heartbeat paper-151-prospective-strategy-recorder at17:15 America/Chicago ACTIVE. No live orders, external messages, backfilled decisions or retuning. Observe through at least October2027. This research turn did NOT run or modify the prospective recorder.

Scripts: ensemble_study.py, ensemble_intraday.py, ensemble_btc_intraday.py, ensemble_all_clocks.py, filing_study.py, macro_study.py, cot_inventory.py, options_weekly.py stage/score, expansion_validate.py, ensemble_report.py. Use .venv/bin/python with PYTHONDONTWRITEBYTECODE=1, LOKY_MAX_CPU_COUNT=4, MPLCONFIGDIR=/tmp/paper151-mpl-cache. Do not run older report generators over this checkpoint. Source projects and external archive are unchanged.
''')
    print('Published ensemble expansion',len(ensemble_rows),'cases',counts,flush=True)

if __name__=='__main__':main()
